// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hello.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *HelloRequest) Validate() error {
	if this.Age != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Age); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Age", err)
		}
	}
	return nil
}
func (this *HelloRequest_Message) Validate() error {
	if !(this.Age > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '0'`, this.Age))
	}
	if !(this.Age < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '100'`, this.Age))
	}
	return nil
}
func (this *HelloResponse) Validate() error {
	return nil
}
